### ISSUE TITLE
Bug to try the example

### ISSUE THREAD

**Issue by IcuScc** [zinkpad/FirmaXadesNet45#1]
Hi. I've test but i get this error message

Se produjo una excepción de tipo 'System.Security.Cryptography.CryptographicException' en System.Security.dll pero no se controló en el código del usuario

Información adicional: Elemento Reference mal formado.

do you know why?

the last week works okey, and suddenly gives this error

Thank you

**Comment by zinkpad** [comment]
Hola IcuScc,

Efectivamente da un error al intentar firmar, he probado con una versión anterior y también da el mismo error,...ahora mismo no sabría decirte cual es el motivo exacto, esta mañana me han funcionado todos los tests correctamente (con Windows 7), pero efectivamente en Windows 10 me está dando problemas. No obstante el error tiene fácil solución ;-), pero quiero revisarlo con más calma la semana que viene.

Muchas gracias por avisar, un saludo!

**Comment by IcuScc** [comment]
Gracias J.Arturo
Lo iba a mirar yo mañana a ver si daba con el causante. No se si lo
conseguire. Jejeje. Si me das una pista, lo puedo comprobar y ayudarte.

Yo tengo windows 8 por si sirve de pista.

Yo la semana pasada con la libreria de hace un año firmaba bien. Y hoy
patapum. Se que se me hizo un windows update esta semana, no se si eso
podria haber sido el detonante.

Gracias J.Arturo, seguimos en contacto

Sergio

**Comment by zinkpad** [comment]
Sustituir el método GetElementId de la clase XadesSignedXml por:
```
public override XmlElement GetIdElement(XmlDocument xmlDocument, string idValue)
        {
            // check to see if it's a standard ID reference
            XmlElement retVal = null;

            if (idValue == this.signedPropertiesIdBuffer)
            {
                retVal = base.GetIdElement(this.cachedXadesObjectDocument, idValue);
               
                if (retVal != null)
                {
                    return retVal;
                }

                // if not, search for custom ids
                foreach (string idAttr in idAttrs)
                {
                    retVal = this.cachedXadesObjectDocument.SelectSingleNode("//*[@" + idAttr + "=\"" + idValue + "\"]") as XmlElement;
                    if (retVal != null)
                    {
                        break;
                    }
                }
            }
            else
            {
                if (xmlDocument != null)
                {
                    retVal = base.GetIdElement(xmlDocument, idValue);
                    if (retVal != null)
                    {
                        return retVal;
                    }

                    // if not, search for custom ids
                    foreach (string idAttr in idAttrs)
                    {
                        retVal = xmlDocument.SelectSingleNode("//*[@" + idAttr + "=\"" + idValue + "\"]") as XmlElement;
                        if (retVal != null)
                        {
                            break;
                        }
                    }
                }
            }

            return retVal;
        }
```
En principio con eso ya no da el error, no he probado a comprobar si la firma resultante es válida,...el problema parece ser que está duplicando el objeto Xades dentro del documento. La semana que viene investigaré cual es el motivo y subiré los cambios.

Un saludo.

**Comment by IcuScc** [comment]
Hola J.Arturo, buenos días, y de antemano Feliz y Buen fin de semana.

He conseguido que me funcione y se me validen las facturas. 😊

Realmente la pista que me diste parece ser buena, bueno parce no, lo ha
sido. :-)
En efecto esta duplicando el objeto XADES. Lo que me extraña es que se haya
empezado a duplicar así de repente. No se si voy a tener la capacidad de
averiguarlo, me considero novato en esto del .NET.

Finalmente la solución que me enviaste y de la cual estoy muy muy muy muy
muy agradecido, no ha funcionado. Aunque ya no da el error, el validador
dice que la firma no es correcta.
Asi que mirando poco a poco, he llegado a la solución siguiente, y de esta
forma no me da error y el validador dice que OK a la firma.

Te marco la linea que he comentado en color ROJO. Si lo miras y das con el
motivo si puedes y te acuerdas me podrias decir que ha sido? y que ha
provocado todo esto?

        public override XmlElement GetIdElement(XmlDocument xmlDocument,
string idValue)
        {
            // check to see if it's a standard ID reference
            XmlElement retVal = null;

            if (idValue == this.signedPropertiesIdBuffer)
            {
                //retVal =
base.GetIdElement(this.cachedXadesObjectDocument, idValue);

                var xmlDocumentCloned = new XmlDocument();
                xmlDocumentCloned.LoadXml(xmlDocument.OuterXml);
               *
//xmlDocumentCloned.DocumentElement.AppendChild(xmlDocumentCloned.ImportNode(cachedXadesObjectDocument.DocumentElement,
true));*
                retVal = base.GetIdElement(xmlDocumentCloned, idValue);

                if (retVal != null)
                {
                    return retVal;
                }

                // if not, search for custom ids
                foreach (string idAttr in idAttrs)
                {
                    retVal =
this.cachedXadesObjectDocument.SelectSingleNode("//*[@" + idAttr + "=\"" +
idValue + "\"]") as XmlElement;
                    if (retVal != null)
                    {
                        break;
                    }
                }
            }
            else
            {
                if (xmlDocument != null)
                {
                    retVal = base.GetIdElement(xmlDocument, idValue);
                    if (retVal != null)
                    {
                        return retVal;
                    }

                    // if not, search for custom ids
                    foreach (string idAttr in idAttrs)
                    {
                        retVal = xmlDocument.SelectSingleNode("//*[@" +
idAttr + "=\"" + idValue + "\"]") as XmlElement;
                        if (retVal != null)
                        {
                            break;
                        }
                    }
                }
            }

            return retVal;
        }


gracias y seguimos en contacto

😉

Sergio
669755277
www.icuscc.com


2016-03-12 0:03 GMT+01:00 J. Arturo <notifications@github.com>:

**Comment by jamalo105** [comment]
Hola, yo he comprobado que puede ser una actualización de Windows, en un ordenador que tengo la librería system.security.dll en Microsoft.net versión 4 de fecha de 2015 funciona correctamente y en otro en el que la librería es de fecha de febrero de 2016 es donde no funciona.

Un saludo
José Antonio.

**Comment by zinkpad** [comment]
Estáis en lo cierto los dos, tiene pinta de haber cambiado algo con la última actualización del framework. Por otro lado el método que puse antes provoca que no se validen las firmas, ya que la huella que genera no es correcta, lo cual no alcanzo a comprender, ya que el elemento del objeto Xades cacheado es el mismo que el del documento… de todos modos creo que el método se puede simplificar así:

```
public override XmlElement GetIdElement(XmlDocument xmlDocument, string idValue)
        {
            // check to see if it's a standard ID reference
            XmlElement retVal = null;

            if (xmlDocument != null)
            {
                retVal = base.GetIdElement(xmlDocument, idValue);

                if (retVal != null)
                {
                    return retVal;
                }

                // if not, search for custom ids
                foreach (string idAttr in idAttrs)
                {
                    retVal = xmlDocument.SelectSingleNode("//*[@" + idAttr + "=\"" + idValue + "\"]") as XmlElement;
                    if (retVal != null)
                    {
                        break;
                    }
                }
            }

            return retVal;
        }
```
Ya que para calcular la huella de las propiedades de la firma se pasan todos los DataObject en xmlDocument, y al que apunta la referencia deberá estar contenido dentro de xmlDocument.

He probado un par de firmas y validan correctamente, no obstante la semana que viene realizaré más pruebas.

Muchas gracias a todos!
